<?php

namespace Proxies\__CG__\ISETKBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Classe extends \ISETKBundle\Entity\Classe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'id', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'niveau', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'filiere', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'classes', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'emploi', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'Matiere');
        }

        return array('__isInitialized__', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'id', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'niveau', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'filiere', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'classes', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'emploi', '' . "\0" . 'ISETKBundle\\Entity\\Classe' . "\0" . 'Matiere');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Classe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau($niveau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', array($niveau));

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', array());

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiliere($filiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiliere', array($filiere));

        return parent::setFiliere($filiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiliere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiliere', array());

        return parent::getFiliere();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasses($classes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasses', array($classes));

        return parent::setClasses($classes);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasses', array());

        return parent::getClasses();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmploi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmploi', array());

        return parent::getEmploi();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmploi($emploi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmploi', array($emploi));

        return parent::setEmploi($emploi);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatiere', array());

        return parent::getMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatiere($Matiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatiere', array($Matiere));

        return parent::setMatiere($Matiere);
    }

}
